version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: dreamsociety-nodejs
    container_name: dreamsociety-nodejs
    restart: unless-stopped 
    ports:
      - "8081:8082"
    volumes:
      - .:/dreamSociety-BE/app
      - node_modules:/dreamSociety-BE/app/node_modules
    networks:
      - app-network
    command: /dreamSociety-BE/app/node_modules/.bin/nodemon app.js

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
